name: Build & Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_01 }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Debug ECS settings
        run: |
          echo "Cluster: ${{ test-app-clusterR }}"
          echo "Service: ${{ task-CI-app-service-woxcO6lu }}"
          echo "Region: ${{ us-east-1 }}"

      - name: Force ECS to pull latest image and redeploy
        run: |
          aws ecs update-service \
            --cluster ${{ test-app-clusterR }} \
            --service ${{ task-CI-app-service-woxcO6lu }} \
            --force-new-deployment \
            --region ${{ us-east-1 }}
